name = "CUBScout"
uuid = "5bb2324b-4f8a-4227-8185-e835854b0a1e"
authors = ["Augustus Pendleton"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
